NEWS=accessible
LIM=125K #human readable
LIM_NUM=125000
DATE=date
DRIVE=hg191

PARENT_DIR=/$DRIVE/corpora/historical_newspapers
DATA_DIR=$PARENT_DIR/$NEWS
FILES_DIR=$PARENT_DIR/files
STATS_DIR=$PARENT_DIR/stats
MODELS_DIR=$PARENT_DIR/models

CORPUS_FILENAME=$NEWS.jsonl
CORPUS_TOKENIZED_FILE=$NEWS.tokenized.jsonl
SAMPLING_RATE=1.0
