DBLP=dblp
LIM=500K #human readable
LIM_NUM=500000
DRIVE=hg190

PARENT_DIR=/$DRIVE/corpora/academic-data/$DBLP
FILES_DIR=$PARENT_DIR/files
STATS_DIR=$PARENT_DIR/stats
MODELS_DIR=$PARENT_DIR/models

CORPUS_FILE=$DBLP.jsonl
CORPUS_TOKENIZED_FILE=$DBLP.tokenized.jsonl
SAMPLING_RATE=0.25
